# Generated by Django 4.2.26 on 2025-12-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_category_post_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(blank=True, to="blog.category"),
        ),
    ]
