# Generated by Django 4.2.26 on 2025-12-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_post_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.CharField(blank=True, default="AnonTrooper", max_length=50),
        ),
    ]
